name: regalia
description: An open source cross-platform mobile twitch client.
version: 1.0.0+1

publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_inappwebview: ^5.4.3+7
  flutter_secure_storage: ^5.0.2
  fpdart: ^0.0.14
  freezed_annotation: ^2.0.3
  go_router: ^3.1.0
  hooks_riverpod: ^2.0.0-dev.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.10
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
