name: regalia
description: An open source cross-platform mobile twitch client.
version: 1.0.0+1

publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_inappwebview: ^5.4.3+7
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.3
  freezed_annotation: ^2.0.3
  go_router: ^4.1.0
  hooks_riverpod: ^2.0.0-dev.9
  intl: ^0.17.0
  json_annotation: ^4.5.0
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.10
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_default_monochrome.svg
    - assets/fonts/OFL.txt
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
        - asset: assets/fonts/Lato-BlackItalic.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-BoldItalic.ttf
        - asset: assets/fonts/Lato-Italic.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-LightItalic.ttf
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Thin.ttf
        - asset: assets/fonts/Lato-ThinItalic.ttf
